"""
Even Fibonacci numbers
Submit

 Show HTML problem content 
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


Answer:  4613732
Completed on Tue, 12 Mar 2013, 08:06
"""
from timeit import default_timer as timer
import os.path as op

# Solution 1
s11 = timer()
a, b, c, sum, upperLim = 1, 2, 0, 2, 4000000
while b <= upperLim:
    c=a+b
    a=b
    b = c
    if c%2 == 0:
        sum += c
print(f"The answer to Project Euler, {op.basename(__file__)[:-3]} is: " + str(sum))
s12 = timer()
print("Time lapsed for solution number 2: " + str((s12-s11)*10**6) + u'\u03BC' + "s")
